# AUTO-GENERATED by AirFlowClone UI. Re-running the form will be rejected
# if this file still exists; delete it first or pick a different dag_id.
from __future__ import annotations

from airflowclone import DAG

dag = DAG(
    dag_id='fooy',
    description='Gets a variable and displays it',
)

@dag.task
def first_task():
    my_key = 'foomyman'
    val = Variable.get(my_key)
    print('got variable:', val)
    return {my_key: val}
